# Exercises

There are three exercises in this notebook:

1. Use the cross-validation method to test the linear regression with different $\alpha$ values, at least three.
2. Implement a SGD method that will train the Lasso regression for 10 epochs.
3. Extend the Fisher's classifier to work with two features. Use the class as the $y$.

## 1. Cross-validation linear regression

You need to change the variable `alpha` to be a list of alphas. Next do a loop and finally compare the results.

In [5]:
import numpy as np
from sklearn.linear_model import Ridge
import pandas as pd

x = np.array([188, 181, 197, 168, 167, 187, 178, 194, 140, 176, 168, 192, 173, 142, 176]).reshape(-1, 1).reshape(15, 1)
y = np.array([141, 106, 149, 59, 79, 136, 65, 136, 52, 87, 115, 140, 82, 69, 121]).reshape(-1, 1).reshape(15, 1)

x = np.asmatrix(np.c_[np.ones((15, 1)), x])

I = np.identity(2)
alphas = [0.01, 0.1, 0.25, 0.5, 0.75, 1.0, 10.0]  # change here

# add 1-3 line of code here
results = []
for alpha in alphas:
    w = np.linalg.inv(x.T * x + alpha * I) * x.T * y
    w = w.ravel()

    ridge = Ridge(alpha=alpha, fit_intercept=False).fit(X=np.asarray(x), y=y)
    results.append(
        (alpha, w.item(0), w.item(1), ridge.coef_.item(0), ridge.coef_.item(1))
    )

# add 1-3 lines to compare the results
df = pd.DataFrame(results, columns=["alpha", "w0", "w1", "w0_sklearn", "w1_sklearn"])
df

   alpha          w0        w1  w0_sklearn  w1_sklearn
0   0.01 -167.855340  1.544160 -167.855340    1.544160
1   0.10 -101.723971  1.169788 -101.723971    1.169788
2   0.25  -61.403292  0.941530  -61.403292    0.941530
3   0.50  -36.975220  0.803242  -36.975220    0.803242
4   0.75  -26.451327  0.743665  -26.451327    0.743665
5   1.00  -20.590447  0.710486  -20.590447    0.710486
6  10.00   -2.291063  0.606881   -2.291063    0.606881

## 2. Implement based on the Ridge regression example, the Lasso regression.

Please implement the SGD method and compare the results with the sklearn Lasso regression results.

In [6]:
def sgd(x, y, lr, alpha, epoch):
    # your code goes here
    rows, cols = x.shape
    weights = np.zeros(cols)

    for _ in range(epoch):
        for i in range(rows):
            xi = x[i]
            yi = y[i]

            y_pred = np.dot(xi, weights)
            error = yi - y_pred

            grad = -2 * xi * error + alpha * np.sign(weights)
            weights -= lr * grad

    return weights

In [7]:
from sklearn.linear_model import Lasso

x = np.array([188, 181, 197, 168, 167, 187, 178, 194, 140, 176, 168, 192, 173, 142, 176]).reshape(-1, 1).reshape(15, 1)
y = np.array([141, 106, 149, 59, 79, 136, 65, 136, 52, 87, 115, 140, 82, 69, 121]).reshape(-1, 1).reshape(15, 1)

x_matrix = np.c_[np.ones((15, 1)), x]
alpha = 0.1

sgd = sgd(x_matrix, y.ravel(), lr=1e-6, alpha=alpha, epoch=10)
print(f"w_sgd: {sgd}")

lasso = Lasso(alpha=alpha)
lasso.fit(x, y.ravel())  # update this line
print(f"lasso_intercept: {lasso.intercept_}, lasso_coef: {lasso.coef_}")

w_sgd: [0.00283717 0.59172102]
lasso_intercept: -180.85790859980537, lasso_coef: [1.61776499]

## 3. Extend the Fisher's classifier

Please extend the targets of the `iris_data` variable and use it as the $y$.

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

iris_data = load_iris()
iris_df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris_df["target"] = iris_data.target

x = iris_df[["sepal width (cm)", "sepal length (cm)"]].values  # change here
y = iris_df["target"].values.reshape(-1, 1)  # change here

dataset_size = np.size(x)

mean_x, mean_y = np.mean(x), np.mean(y)

SS_xy = np.sum(y * x) - dataset_size * mean_y * mean_x
SS_xx = np.sum(x * x) - dataset_size * mean_x * mean_x

a = SS_xy / SS_xx
b = mean_y - a * mean_x


y_pred = a * x + b

df = pd.DataFrame(y_pred, columns=["", ""])
df

0    0.924785  1.051418
1    0.885212  1.035589
2    0.901042  1.019760
3    0.893127  1.011845
4    0.932700  1.043504
..        ...       ...
145  0.885212  1.178051
146  0.845640  1.146393
147  0.885212  1.162222
148  0.916871  1.138479
149  0.885212  1.114735

[150 rows x 2 columns]